language: r
cache: packages

r_packages:
  - netmhc2pan

r_github_packages:
  - jimhester/covr
  - jimhester/lintr

before_script:
  # tcsh
  - sudo apt install tcsh
  # NetMHC2pan
  - Rscript -e 'netmhc2pan::install_netmhc2pan()'

after_success:
  - Rscript -e 'lintr::lint_package()'
  - Rscript -e 'covr::codecov()'
  - Rscript -e 'goodpractice::gp()'
  # Download thesis
  - wget https://www.rug.nl/research/portal/files/132028374/Complete_thesis.pdf

after_failure:
  - wget https://www.rug.nl/research/portal/files/132028374/Complete_thesis.pdf

